CREATE PIPE SNOWFLAKE_TECH_TALK_TEST_2.TEST.ITEM_CATALOG_PIPE 
  AUTO_INGEST=TRUE AS
  COPY INTO SNOWFLAKE_TECH_TALK_TEST_2.TEST.WEB_APP
  FROM @SNOWFLAKE_TECH_TALK_TEST_2.TEST.TECH_TALK_TEST_STAGE_2/data
  FILE_FORMAT = SNOWFLAKE_TECH_TALK_TEST_2.TEST.GZIP_FILE_FORMAT;