CREATE OR REPLACE PIPE TECH_TALK.PUBLIC.WEB_APP_FORM_PIPE
  AUTO_INGEST=TRUE AS
  COPY INTO TECH_TALK.PUBLIC.WEB_APP
  FROM @TECH_TALK.PUBLIC.TECH_TALK_STAGE
  FILE_FORMAT = TECH_TALK.PUBLIC.GZIP_FILE_FORMAT;